[font]
normal = { family = "IBM Plex Mono", style = "Regular" }
# normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "IBM Plex Mono", style = "Bold" }
# bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "IBM Plex Mono", style = "Italic" }
# italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
