[colors]

[colors.primary]
background = '#00141A'
foreground = '#d3c6aa'

[colors.normal]
black   = '#586E75'
red     = '#B7211F'
green   = '#596600'
yellow  = '#B58900'
blue    = '#1B6497'
magenta = '#B02669'
cyan    = '#1A6265'
white   = '#FDF6E3'

[colors.bright]
black   = '#586E75'
red     = '#B7211F'
green   = '#596600'
yellow  = '#B58900'
blue    = '#1B6497'
magenta = '#B02669'
cyan    = '#1A6265'
white   = '#FDF6E3'


